name: CI/CD Pipeline - Customer Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Test Spring Boot Application
        run: |
          cd customer-service
          mvn clean package 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Services with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 15  # Wait for services to start
          docker ps  # Verify running containers

      - name: Shut Down Docker Compose
        run: docker-compose down

  push-to-dockerhub:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Customer Service Image
        run: |
          cd customer-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/customer-service:latest .

      - name: Push Customer Service Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/customer-service:latest
