name: CI/CD Pipeline - Customer Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Build and Run Services with Docker Compose
        run: |
          ls -la  # hekps to Ensure mysql and redis directories exist
          docker-compose up -d --build
          echo "Waiting for services to start..."
          sleep 20  # time to services to initialize
          docker ps  #  running containers

      - name: Shut Down Docker Compose
        run: docker-compose down

  push-to-dockerhub:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Only `customer-service-adv`
        run: |
          docker-compose build customer-service
          docker tag abhilashmedaboina/dockerone:customer-service-adv ${{ secrets.DOCKER_USERNAME }}/customer-service-adv:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/customer-service-adv:latest
