name: CI/CD Pipeline - Customer Service (Docker Compose)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (required for pulling/pushing images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and start services using Docker Compose
      - name: Build and Run Services with Docker Compose
        run: |
          docker-compose up -d --build
          echo "Waiting for services to start..."
          sleep 20  # Allow services to initialize
          docker ps  # Verify running containers

      # Run tests inside the customer-service container
      - name: Run Tests Inside Customer Service Container
        run: |
          docker exec customer-service mvn test

      # Shut down Docker Compose after tests
      - name: Shut Down Docker Compose
        run: docker-compose down

  push-to-dockerhub:
    needs: build-test  # Ensure this job runs only after build-test succeeds
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the customer-service image to Docker Hub
      - name: Build and Push Customer Service Image
        run: |
          docker-compose build customer-service  # Build only the customer-service image
          docker tag abhilashmedaboina/dockerone:customer-service-adv ${{ secrets.DOCKER_USERNAME }}/dockerone:customer-service-adv
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerone:customer-service-adv